/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

union _1_fac_$node;
struct _IO_FILE;
enum _1_fac_$op;
struct timespec;
enum _1_fib_$op;
union _1_fib_$node;
struct timeval;
extern int gettimeofday(struct timeval *tv, void *tz);
extern int pthread_cond_broadcast(int *cond);
char **_global_argv = (char **)0;
extern int posix_memalign(void **memptr, unsigned int alignment, unsigned int size);
extern int getpagesize();
char const *_1_fac_$strings = "fac(%i)=%i\n\000";
extern int pthread_join(void *thread, void **value_ptr);
extern unsigned int strlen(char const *s);
extern int open(char const *filename, int oflag, ...);
enum _1_fac_$op
{
  _1_fac__string$result_STA_0$value_LIT_0 = 123,
  _1_fac__constant_int$result_STA_0$value_LIT_0 = 132,
  _1_fac__formal$result_STA_0$value_LIT_0 = 3,
  _1_fac__returnVoid$ = 90,
  _1_fac__goto$label_LAB_0 = 91,
  _1_fac__convert_void_star2void_star$left_STA_0$result_STA_0 = 58,
  _1_fac__load_int$left_STA_0$result_STA_0 = 103,
  _1_fac__local$result_STA_0$value_LIT_0 = 100,
  _1_fac__branchIfTrue$expr_STA_0$label_LAB_0 = 154,
  _1_fac__Le_int_int2int$right_STA_0$result_STA_0$left_STA_1 = 136,
  _1_fac__Mult_int_int2int$right_STA_0$result_STA_0$left_STA_1 = 190,
  _1_fac__store_void_star$left_STA_0$right_STA_1 = 163,
  _1_fac__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1 = 7,
  _1_fac__store_int$left_STA_0$right_STA_1 = 1,
  _1_fac__call$func_LIT_0 = 64
};
unsigned char _1_fac_$array[1][149] = {{_1_fac__constant_int$result_STA_0$value_LIT_0, (unsigned char)1, (unsigned char)0, (unsigned char)0,
                                        (unsigned char)0, _1_fac__local$result_STA_0$value_LIT_0, (unsigned char)4, (unsigned char)0,
                                        (unsigned char)0, (unsigned char)0, _1_fac__store_int$left_STA_0$right_STA_1, _1_fac__constant_int$result_STA_0$value_LIT_0,
                                        (unsigned char)2, (unsigned char)0, (unsigned char)0, (unsigned char)0,
                                        _1_fac__local$result_STA_0$value_LIT_0, (unsigned char)8, (unsigned char)0, (unsigned char)0,
                                        (unsigned char)0, _1_fac__store_int$left_STA_0$right_STA_1, _1_fac__goto$label_LAB_0, (unsigned char)4,
                                        (unsigned char)0, (unsigned char)0, (unsigned char)0, _1_fac__local$result_STA_0$value_LIT_0,
                                        (unsigned char)8, (unsigned char)0, (unsigned char)0, (unsigned char)0,
                                        _1_fac__load_int$left_STA_0$result_STA_0, _1_fac__formal$result_STA_0$value_LIT_0, (unsigned char)0, (unsigned char)0,
                                        (unsigned char)0, (unsigned char)0, _1_fac__load_int$left_STA_0$result_STA_0, _1_fac__Le_int_int2int$right_STA_0$result_STA_0$left_STA_1,
                                        _1_fac__branchIfTrue$expr_STA_0$label_LAB_0, (unsigned char)14, (unsigned char)0, (unsigned char)0,
                                        (unsigned char)0, _1_fac__goto$label_LAB_0, (unsigned char)4, (unsigned char)0,
                                        (unsigned char)0, (unsigned char)0, _1_fac__goto$label_LAB_0, (unsigned char)51,
                                        (unsigned char)0, (unsigned char)0, (unsigned char)0, _1_fac__local$result_STA_0$value_LIT_0,
                                        (unsigned char)4, (unsigned char)0, (unsigned char)0, (unsigned char)0,
                                        _1_fac__load_int$left_STA_0$result_STA_0, _1_fac__local$result_STA_0$value_LIT_0, (unsigned char)8, (unsigned char)0,
                                        (unsigned char)0, (unsigned char)0, _1_fac__load_int$left_STA_0$result_STA_0, _1_fac__Mult_int_int2int$right_STA_0$result_STA_0$left_STA_1,
                                        _1_fac__local$result_STA_0$value_LIT_0, (unsigned char)4, (unsigned char)0, (unsigned char)0,
                                        (unsigned char)0, _1_fac__store_int$left_STA_0$right_STA_1, _1_fac__local$result_STA_0$value_LIT_0, (unsigned char)8,
                                        (unsigned char)0, (unsigned char)0, (unsigned char)0, _1_fac__load_int$left_STA_0$result_STA_0,
                                        _1_fac__constant_int$result_STA_0$value_LIT_0, (unsigned char)1, (unsigned char)0, (unsigned char)0,
                                        (unsigned char)0, _1_fac__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1, _1_fac__local$result_STA_0$value_LIT_0, (unsigned char)8,
                                        (unsigned char)0, (unsigned char)0, (unsigned char)0, _1_fac__store_int$left_STA_0$right_STA_1,
                                        _1_fac__goto$label_LAB_0, (unsigned char)190, (unsigned char)255, (unsigned char)255,
                                        (unsigned char)255, _1_fac__goto$label_LAB_0, (unsigned char)185, (unsigned char)255,
                                        (unsigned char)255, (unsigned char)255, _1_fac__string$result_STA_0$value_LIT_0, (unsigned char)0,
                                        (unsigned char)0, (unsigned char)0, (unsigned char)0, _1_fac__convert_void_star2void_star$left_STA_0$result_STA_0,
                                        _1_fac__local$result_STA_0$value_LIT_0, (unsigned char)16, (unsigned char)0, (unsigned char)0,
                                        (unsigned char)0, _1_fac__store_void_star$left_STA_0$right_STA_1, _1_fac__formal$result_STA_0$value_LIT_0, (unsigned char)0,
                                        (unsigned char)0, (unsigned char)0, (unsigned char)0, _1_fac__load_int$left_STA_0$result_STA_0,
                                        _1_fac__local$result_STA_0$value_LIT_0, (unsigned char)24, (unsigned char)0, (unsigned char)0,
                                        (unsigned char)0, _1_fac__store_int$left_STA_0$right_STA_1, _1_fac__local$result_STA_0$value_LIT_0, (unsigned char)4,
                                        (unsigned char)0, (unsigned char)0, (unsigned char)0, _1_fac__load_int$left_STA_0$result_STA_0,
                                        _1_fac__local$result_STA_0$value_LIT_0, (unsigned char)28, (unsigned char)0, (unsigned char)0,
                                        (unsigned char)0, _1_fac__store_int$left_STA_0$right_STA_1, _1_fac__call$func_LIT_0, (unsigned char)1,
                                        (unsigned char)0, (unsigned char)0, (unsigned char)0, _1_fac__goto$label_LAB_0,
                                        (unsigned char)4, (unsigned char)0, (unsigned char)0, (unsigned char)0,
                                        _1_fac__returnVoid$}};
extern int pthread_barrier_destroy(int *barrier);
extern int pthread_mutex_init(int *mutex, int *attr);
extern int strncmp(char const *s1, char const *s2, unsigned int maxlen);
typedef long __syscall_slong_t;
typedef long __time_t;
struct timespec
{
  __time_t tv_sec;
  __syscall_slong_t tv_nsec;
};
extern int printf(char const *__restrict __format, ...);
int _global_argc = 0;
extern int pthread_cond_signal(int *cond);
extern int pthread_barrier_init(int *barrier, int *attr, unsigned int count);
extern int raise(int sig);
extern int scanf(char const *format, ...);
char **_global_envp = (char **)0;
extern int unlink(char const *filename);
union _1_fib_$node
{
  char _char;
  unsigned int _unsigned_int;
  unsigned char _unsigned_char;
  long _long;
  unsigned long _unsigned_long;
  void *_void_star;
  unsigned short _unsigned_short;
  unsigned long long _unsigned_long_long;
  signed char _signed_char;
  long long _long_long;
  int _int;
  short _short;
};
extern int pthread_barrier_wait(int *barrier);
extern double difftime(long tv1, long tv0);
extern void *memcpy(void *s1, void const *s2, unsigned int size);
extern int pthread_mutex_lock(int *mutex);
extern void *dlsym(void *handle, char *symbol);
extern int gethostname(char *name, unsigned int namelen);
extern void abort();
extern unsigned long strtoul(char const *str, char const *endptr, int base);
extern void free(void *ptr);
extern int fprintf(struct _IO_FILE *stream, char const *format, ...);
union _1_fac_$node
{
  char _char;
  unsigned int _unsigned_int;
  unsigned char _unsigned_char;
  long _long;
  unsigned long _unsigned_long;
  void *_void_star;
  unsigned short _unsigned_short;
  unsigned long long _unsigned_long_long;
  signed char _signed_char;
  long long _long_long;
  int _int;
  short _short;
};
extern void exit(int status);
extern void signal(int sig, void *func);
int main(int argc, char **argv, char **_formal_envp);
char const *_1_fib_$strings = "fib(%i)=%i\n\000";
typedef struct _IO_FILE FILE;
extern int mprotect(void *addr, unsigned int len, int prot);
extern int close(int filedes);
extern double log(double x);
extern double strtod(char const *str, char const *endptr);
extern double ceil(double x);
extern int fcntl(int filedes, int cmd, ...);
extern int fclose(void *stream);
extern void perror(char const *str);
extern int pthread_cond_wait(int *cond, int *mutex);
void fac(int n);
extern int write(int filedes, void *buf, unsigned int nbyte);
extern int pthread_cond_init(int *cond, int *attr);
extern int ptrace(int request, void *pid, void *addr, int data);
extern unsigned int strnlen(char const *s, unsigned int maxlen);
extern float strtof(char const *str, char const *endptr);
struct timeval
{
  long tv_sec;
  long tv_usec;
};
extern void qsort(void *base, unsigned int nel, unsigned int width, int (*compar)(void *a, void *b));
extern long clock(void);
extern long time(long *tloc);
extern int read(int filedes, void *buf, unsigned int nbyte);
extern int rand();
enum _1_fib_$op
{
  _1_fib__branchIfTrue$expr_STA_0$label_LAB_0 = 120,
  _1_fib__constant_int$result_STA_0$value_LIT_0 = 55,
  _1_fib__formal$result_STA_0$value_LIT_0 = 11,
  _1_fib__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1 = 250,
  _1_fib__returnVoid$ = 178,
  _1_fib__goto$label_LAB_0 = 87,
  _1_fib__convert_void_star2void_star$left_STA_0$result_STA_0 = 227,
  _1_fib__string$result_STA_0$value_LIT_0 = 255,
  _1_fib__store_int$left_STA_0$right_STA_1 = 2,
  _1_fib__Lt_int_int2int$left_STA_0$result_STA_0$right_STA_1 = 202,
  _1_fib__load_int$left_STA_0$result_STA_0 = 173,
  _1_fib__local$result_STA_0$value_LIT_0 = 154,
  _1_fib__call$func_LIT_0 = 74,
  _1_fib__store_void_star$left_STA_0$right_STA_1 = 220
};
extern int strcmp(char const *a, char const *b);
extern void *fopen(char const *filename, char const *mode);
extern double sqrt(double x);
extern long strtol(char const *str, char const *endptr, int base);
extern int snprintf(char *str, unsigned int size, char const *format, ...);
extern void *malloc(unsigned int size);
extern int nanosleep(struct timespec const *__requested_time, struct timespec *__remaining);
extern int pthread_mutex_unlock(int *mutex);
extern int atoi(char const *s);
extern int pthread_create(void *thread, void *attr, void *start_routine, void *arg);
unsigned char _1_fib_$array[1][195] = {{_1_fib__constant_int$result_STA_0$value_LIT_0, (unsigned char)0, (unsigned char)0, (unsigned char)0,
                                        (unsigned char)0, _1_fib__local$result_STA_0$value_LIT_0, (unsigned char)4, (unsigned char)0,
                                        (unsigned char)0, (unsigned char)0, _1_fib__store_int$left_STA_0$right_STA_1, _1_fib__constant_int$result_STA_0$value_LIT_0,
                                        (unsigned char)1, (unsigned char)0, (unsigned char)0, (unsigned char)0,
                                        _1_fib__local$result_STA_0$value_LIT_0, (unsigned char)8, (unsigned char)0, (unsigned char)0,
                                        (unsigned char)0, _1_fib__store_int$left_STA_0$right_STA_1, _1_fib__constant_int$result_STA_0$value_LIT_0, (unsigned char)1,
                                        (unsigned char)0, (unsigned char)0, (unsigned char)0, _1_fib__local$result_STA_0$value_LIT_0,
                                        (unsigned char)12, (unsigned char)0, (unsigned char)0, (unsigned char)0,
                                        _1_fib__store_int$left_STA_0$right_STA_1, _1_fib__constant_int$result_STA_0$value_LIT_0, (unsigned char)1, (unsigned char)0,
                                        (unsigned char)0, (unsigned char)0, _1_fib__local$result_STA_0$value_LIT_0, (unsigned char)16,
                                        (unsigned char)0, (unsigned char)0, (unsigned char)0, _1_fib__store_int$left_STA_0$right_STA_1,
                                        _1_fib__goto$label_LAB_0, (unsigned char)4, (unsigned char)0, (unsigned char)0,
                                        (unsigned char)0, _1_fib__formal$result_STA_0$value_LIT_0, (unsigned char)0, (unsigned char)0,
                                        (unsigned char)0, (unsigned char)0, _1_fib__load_int$left_STA_0$result_STA_0, _1_fib__local$result_STA_0$value_LIT_0,
                                        (unsigned char)16, (unsigned char)0, (unsigned char)0, (unsigned char)0,
                                        _1_fib__load_int$left_STA_0$result_STA_0, _1_fib__Lt_int_int2int$left_STA_0$result_STA_0$right_STA_1, _1_fib__branchIfTrue$expr_STA_0$label_LAB_0, (unsigned char)14,
                                        (unsigned char)0, (unsigned char)0, (unsigned char)0, _1_fib__goto$label_LAB_0,
                                        (unsigned char)4, (unsigned char)0, (unsigned char)0, (unsigned char)0,
                                        _1_fib__goto$label_LAB_0, (unsigned char)75, (unsigned char)0, (unsigned char)0,
                                        (unsigned char)0, _1_fib__local$result_STA_0$value_LIT_0, (unsigned char)4, (unsigned char)0,
                                        (unsigned char)0, (unsigned char)0, _1_fib__load_int$left_STA_0$result_STA_0, _1_fib__local$result_STA_0$value_LIT_0,
                                        (unsigned char)8, (unsigned char)0, (unsigned char)0, (unsigned char)0,
                                        _1_fib__load_int$left_STA_0$result_STA_0, _1_fib__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1, _1_fib__local$result_STA_0$value_LIT_0, (unsigned char)12,
                                        (unsigned char)0, (unsigned char)0, (unsigned char)0, _1_fib__store_int$left_STA_0$right_STA_1,
                                        _1_fib__local$result_STA_0$value_LIT_0, (unsigned char)8, (unsigned char)0, (unsigned char)0,
                                        (unsigned char)0, _1_fib__load_int$left_STA_0$result_STA_0, _1_fib__local$result_STA_0$value_LIT_0, (unsigned char)4,
                                        (unsigned char)0, (unsigned char)0, (unsigned char)0, _1_fib__store_int$left_STA_0$right_STA_1,
                                        _1_fib__local$result_STA_0$value_LIT_0, (unsigned char)12, (unsigned char)0, (unsigned char)0,
                                        (unsigned char)0, _1_fib__load_int$left_STA_0$result_STA_0, _1_fib__local$result_STA_0$value_LIT_0, (unsigned char)8,
                                        (unsigned char)0, (unsigned char)0, (unsigned char)0, _1_fib__store_int$left_STA_0$right_STA_1,
                                        _1_fib__local$result_STA_0$value_LIT_0, (unsigned char)16, (unsigned char)0, (unsigned char)0,
                                        (unsigned char)0, _1_fib__load_int$left_STA_0$result_STA_0, _1_fib__constant_int$result_STA_0$value_LIT_0, (unsigned char)1,
                                        (unsigned char)0, (unsigned char)0, (unsigned char)0, _1_fib__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1,
                                        _1_fib__local$result_STA_0$value_LIT_0, (unsigned char)16, (unsigned char)0, (unsigned char)0,
                                        (unsigned char)0, _1_fib__store_int$left_STA_0$right_STA_1, _1_fib__goto$label_LAB_0, (unsigned char)166,
                                        (unsigned char)255, (unsigned char)255, (unsigned char)255, _1_fib__goto$label_LAB_0,
                                        (unsigned char)161, (unsigned char)255, (unsigned char)255, (unsigned char)255,
                                        _1_fib__string$result_STA_0$value_LIT_0, (unsigned char)0, (unsigned char)0, (unsigned char)0,
                                        (unsigned char)0, _1_fib__convert_void_star2void_star$left_STA_0$result_STA_0, _1_fib__local$result_STA_0$value_LIT_0, (unsigned char)24,
                                        (unsigned char)0, (unsigned char)0, (unsigned char)0, _1_fib__store_void_star$left_STA_0$right_STA_1,
                                        _1_fib__formal$result_STA_0$value_LIT_0, (unsigned char)0, (unsigned char)0, (unsigned char)0,
                                        (unsigned char)0, _1_fib__load_int$left_STA_0$result_STA_0, _1_fib__local$result_STA_0$value_LIT_0, (unsigned char)32,
                                        (unsigned char)0, (unsigned char)0, (unsigned char)0, _1_fib__store_int$left_STA_0$right_STA_1,
                                        _1_fib__local$result_STA_0$value_LIT_0, (unsigned char)12, (unsigned char)0, (unsigned char)0,
                                        (unsigned char)0, _1_fib__load_int$left_STA_0$result_STA_0, _1_fib__local$result_STA_0$value_LIT_0, (unsigned char)36,
                                        (unsigned char)0, (unsigned char)0, (unsigned char)0, _1_fib__store_int$left_STA_0$right_STA_1,
                                        _1_fib__call$func_LIT_0, (unsigned char)1, (unsigned char)0, (unsigned char)0,
                                        (unsigned char)0, _1_fib__goto$label_LAB_0, (unsigned char)4, (unsigned char)0,
                                        (unsigned char)0, (unsigned char)0, _1_fib__returnVoid$}};
extern int fscanf(struct _IO_FILE *stream, char const *format, ...);
extern int fseek(struct _IO_FILE *stream, long offs, int whence);
void megaInit(void);
void fib(int n);

void megaInit(void)
{
  {
  }
}

void fac(int n)
{
  char _1_fac_$locals[32];
  union _1_fac_$node _1_fac_$stack[1][32];
  union _1_fac_$node *_1_fac_$sp[1];
  unsigned char *_1_fac_$pc[1];

  {
    _1_fac_$sp[0] = _1_fac_$stack[0];
    _1_fac_$pc[0] = _1_fac_$array[0];
    while (1)
    {
      switch (*(_1_fac_$pc[0]))
      {
      case _1_fac__local$result_STA_0$value_LIT_0:
        (_1_fac_$pc[0])++;
        (_1_fac_$sp[0] + 1)->_void_star = (void *)(_1_fac_$locals + *((int *)_1_fac_$pc[0]));
        (_1_fac_$sp[0])++;
        _1_fac_$pc[0] += 4;
        break;
      case _1_fac__store_int$left_STA_0$right_STA_1:
        (_1_fac_$pc[0])++;
        *((int *)(_1_fac_$sp[0] + 0)->_void_star) = (_1_fac_$sp[0] + -1)->_int;
        _1_fac_$sp[0] += -2;
        break;
      case _1_fac__convert_void_star2void_star$left_STA_0$result_STA_0:
        (_1_fac_$pc[0])++;
        (_1_fac_$sp[0] + 0)->_void_star = (_1_fac_$sp[0] + 0)->_void_star;
        break;
      case _1_fac__Mult_int_int2int$right_STA_0$result_STA_0$left_STA_1:
        (_1_fac_$pc[0])++;
        (_1_fac_$sp[0] + -1)->_int = (_1_fac_$sp[0] + -1)->_int * (_1_fac_$sp[0] + 0)->_int;
        (_1_fac_$sp[0])--;
        break;
      case _1_fac__returnVoid$:
        (_1_fac_$pc[0])++;
        return;
        break;
      case _1_fac__constant_int$result_STA_0$value_LIT_0:
        (_1_fac_$pc[0])++;
        (_1_fac_$sp[0] + 1)->_int = *((int *)_1_fac_$pc[0]);
        (_1_fac_$sp[0])++;
        _1_fac_$pc[0] += 4;
        break;
      case _1_fac__load_int$left_STA_0$result_STA_0:
        (_1_fac_$pc[0])++;
        (_1_fac_$sp[0] + 0)->_int = *((int *)(_1_fac_$sp[0] + 0)->_void_star);
        break;
      case _1_fac__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1:
        (_1_fac_$pc[0])++;
        (_1_fac_$sp[0] + -1)->_int = (_1_fac_$sp[0] + -1)->_int + (_1_fac_$sp[0] + 0)->_int;
        (_1_fac_$sp[0])--;
        break;
      case _1_fac__call$func_LIT_0:
        (_1_fac_$pc[0])++;
        switch (*((int *)_1_fac_$pc[0]))
        {
        case 1:
          printf(*((char const *__restrict *)(_1_fac_$locals + 16)), *((int *)(_1_fac_$locals + 24)),
                 *((int *)(_1_fac_$locals + 28)));
          break;
        }
        _1_fac_$pc[0] += 4;
        break;
      case _1_fac__branchIfTrue$expr_STA_0$label_LAB_0:
        (_1_fac_$pc[0])++;
        if ((_1_fac_$sp[0] + 0)->_int)
        {
          _1_fac_$pc[0] += *((int *)_1_fac_$pc[0]);
        }
        else
        {
          _1_fac_$pc[0] += 4;
        }
        (_1_fac_$sp[0])--;
        break;
      case _1_fac__formal$result_STA_0$value_LIT_0:
        (_1_fac_$pc[0])++;
        switch (*((int *)_1_fac_$pc[0]))
        {
        case 0:
          (_1_fac_$sp[0] + 1)->_void_star = (void *)(&n);
          break;
        }
        (_1_fac_$sp[0])++;
        _1_fac_$pc[0] += 4;
        break;
      case _1_fac__string$result_STA_0$value_LIT_0:
        (_1_fac_$pc[0])++;
        (_1_fac_$sp[0] + 1)->_void_star = (void *)(_1_fac_$strings + *((int *)_1_fac_$pc[0]));
        (_1_fac_$sp[0])++;
        _1_fac_$pc[0] += 4;
        break;
      case _1_fac__store_void_star$left_STA_0$right_STA_1:
        (_1_fac_$pc[0])++;
        *((void **)(_1_fac_$sp[0] + 0)->_void_star) = (_1_fac_$sp[0] + -1)->_void_star;
        _1_fac_$sp[0] += -2;
        break;
      case _1_fac__goto$label_LAB_0:
        (_1_fac_$pc[0])++;
        _1_fac_$pc[0] += *((int *)_1_fac_$pc[0]);
        break;
      case _1_fac__Le_int_int2int$right_STA_0$result_STA_0$left_STA_1:
        (_1_fac_$pc[0])++;
        (_1_fac_$sp[0] + -1)->_int = (_1_fac_$sp[0] + -1)->_int <= (_1_fac_$sp[0] + 0)->_int;
        (_1_fac_$sp[0])--;
        break;
      }
    }
  }
}
int main(int argc, char **argv, char **_formal_envp)
{
  int _BARRIER_0;

  {
    megaInit();
    _global_argc = argc;
    _global_argv = argv;
    _global_envp = _formal_envp;
    _BARRIER_0 = 1;
    fac(1);
    fib(1);
    fac(5);
    fib(5);
    fac(10);
    fib(10);
    return (0);
  }
}
void fib(int n)
{
  char _1_fib_$locals[40];
  union _1_fib_$node _1_fib_$stack[1][32];
  union _1_fib_$node *_1_fib_$sp[1];
  unsigned char *_1_fib_$pc[1];

  {
    _1_fib_$sp[0] = _1_fib_$stack[0]; // sp is stack pointer
    _1_fib_$pc[0] = _1_fib_$array[0]; // pc is position counter/instruction pointer
    while (1)
    {
      switch (*(_1_fib_$pc[0]))
      {
      case _1_fib__branchIfTrue$expr_STA_0$label_LAB_0:
        (_1_fib_$pc[0])++;
        if ((_1_fib_$sp[0] + 0)->_int)
        {
          _1_fib_$pc[0] += *((int *)_1_fib_$pc[0]);
        }
        else
        {
          _1_fib_$pc[0] += 4;
        }
        (_1_fib_$sp[0])--;
        break;
      case _1_fib__string$result_STA_0$value_LIT_0:
        (_1_fib_$pc[0])++;
        (_1_fib_$sp[0] + 1)->_void_star = (void *)(_1_fib_$strings + *((int *)_1_fib_$pc[0]));
        (_1_fib_$sp[0])++;
        _1_fib_$pc[0] += 4;
        break;
      case _1_fib__load_int$left_STA_0$result_STA_0:
        (_1_fib_$pc[0])++;
        (_1_fib_$sp[0] + 0)->_int = *((int *)(_1_fib_$sp[0] + 0)->_void_star);
        break;
      case _1_fib__convert_void_star2void_star$left_STA_0$result_STA_0:
        (_1_fib_$pc[0])++;
        (_1_fib_$sp[0] + 0)->_void_star = (_1_fib_$sp[0] + 0)->_void_star;
        break;
      case _1_fib__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1:
        (_1_fib_$pc[0])++;
        (_1_fib_$sp[0] + -1)->_int = (_1_fib_$sp[0] + -1)->_int + (_1_fib_$sp[0] + 0)->_int;
        (_1_fib_$sp[0])--;
        break;
      case _1_fib__store_void_star$left_STA_0$right_STA_1:
        (_1_fib_$pc[0])++;
        *((void **)(_1_fib_$sp[0] + 0)->_void_star) = (_1_fib_$sp[0] + -1)->_void_star;
        _1_fib_$sp[0] += -2;
        break;
      case _1_fib__local$result_STA_0$value_LIT_0:
        (_1_fib_$pc[0])++;
        (_1_fib_$sp[0] + 1)->_void_star = (void *)(_1_fib_$locals + *((int *)_1_fib_$pc[0]));
        (_1_fib_$sp[0])++;
        _1_fib_$pc[0] += 4;
        break;
      case _1_fib__constant_int$result_STA_0$value_LIT_0:
        (_1_fib_$pc[0])++;
        (_1_fib_$sp[0] + 1)->_int = *((int *)_1_fib_$pc[0]);
        (_1_fib_$sp[0])++;
        _1_fib_$pc[0] += 4;
        break;
      case _1_fib__formal$result_STA_0$value_LIT_0:
        (_1_fib_$pc[0])++;
        switch (*((int *)_1_fib_$pc[0]))
        {
        case 0:
          (_1_fib_$sp[0] + 1)->_void_star = (void *)(&n);
          break;
        }
        (_1_fib_$sp[0])++;
        _1_fib_$pc[0] += 4;
        break;
      case _1_fib__returnVoid$:
        (_1_fib_$pc[0])++;
        return;
        break;
      case _1_fib__goto$label_LAB_0:
        (_1_fib_$pc[0])++;
        _1_fib_$pc[0] += *((int *)_1_fib_$pc[0]);
        break;
      case _1_fib__Lt_int_int2int$left_STA_0$result_STA_0$right_STA_1:
        (_1_fib_$pc[0])++;
        (_1_fib_$sp[0] + -1)->_int = (_1_fib_$sp[0] + 0)->_int < (_1_fib_$sp[0] + -1)->_int;
        (_1_fib_$sp[0])--;
        break;
      case _1_fib__call$func_LIT_0:
        (_1_fib_$pc[0])++;
        switch (*((int *)_1_fib_$pc[0]))
        {
        case 1:
          printf(*((char const *__restrict *)(_1_fib_$locals + 24)), *((int *)(_1_fib_$locals + 32)),
                 *((int *)(_1_fib_$locals + 36)));
          break;
        }
        _1_fib_$pc[0] += 4;
        break;
      case _1_fib__store_int$left_STA_0$right_STA_1:
        (_1_fib_$pc[0])++;
        *((int *)(_1_fib_$sp[0] + 0)->_void_star) = (_1_fib_$sp[0] + -1)->_int;
        _1_fib_$sp[0] += -2;
        break;
      }
    }
  }
}
